#include "mips/mips32_instr.h"

#include "mips32_qtables.h"

void mips32_load_qtables(
	void
){
	MIPS32_REG_TO_ROLE_TABLE[R0] = 0; // zero
	MIPS32_REG_TO_ROLE_TABLE[R1] = 0; // asm
	MIPS32_REG_TO_ROLE_TABLE[R2] = REG_RETURN;
	MIPS32_REG_TO_ROLE_TABLE[R3] = REG_RETURN;
	MIPS32_REG_TO_ROLE_TABLE[R4] = REG_STACK;
	MIPS32_REG_TO_ROLE_TABLE[R5] = REG_STACK;
	MIPS32_REG_TO_ROLE_TABLE[R6] = REG_STACK;
	MIPS32_REG_TO_ROLE_TABLE[R7] = REG_STACK;
	MIPS32_REG_TO_ROLE_TABLE[R8] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R9] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R10] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R11] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R12] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R13] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R14] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R15] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R16] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R17] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R18] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R19] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R20] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R21] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R22] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R23] = REG_PRESERVE;
	MIPS32_REG_TO_ROLE_TABLE[R24] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R25] = REG_TEMP;
	MIPS32_REG_TO_ROLE_TABLE[R26] = 0;
	MIPS32_REG_TO_ROLE_TABLE[R27] = 0;
	MIPS32_REG_TO_ROLE_TABLE[R28] = REG_MEM_PTR;
	MIPS32_REG_TO_ROLE_TABLE[R29] = REG_STACK_PTR;
	MIPS32_REG_TO_ROLE_TABLE[R30] = REG_MEM_PTR;
	MIPS32_REG_TO_ROLE_TABLE[R31] = REG_MEM_PTR;

	MIPS32_TO_IR_TABLE[0b100000] = IR_ADD_I32; // add
}

